== Relying Party Requirements

*[ODP-RP01]* _Reference <<OIDC>> Section 3.1.2.1

====
ui_locales:: OPTIONAL. End-User's preferred languages and scripts for the
user interface, represented as a space-separated list of BCP47 <<RFC5646>>
language tag values, ordered by preference. For instance, the value "fr-CA fr
en" represents a preference for French as spoken in Canada, then French (without
a region designation), followed by English (without a region designation). An
error SHOULD NOT result if some or all of the requested locales are not
supported by the OpenID Provider.
====
*CATS Support*: _Constrained_

The `ui_locales` parameter is REQUIRED and MUST specify the user's preferred
official language.

_Typically the value will be either `en-CA` or `fr-CA`._

=== CATS-Specific Requirements

==== Single Logout

*[ODP-RP02]*

RPs implementations SHOULD support OpenID back-channel logout <<OIDC-BC>> for
the receipt of logout tokens. An SP MAY support the OpenID front-channel logout
<<OIDC-FC>> in the event that their implementation does not support <<OIDC-BC>>.