=== CATS-Specific Requirements

==== Metadata Content

*[CDP-IDP01]*

In addition to the requirements of *[SDP-IDP31]*, an IdP’s metadata MUST also
contain the levels of assurance to which it conforms, as specified by the
Identity Assurance Certification Attribute Profile <<SAML2Assur>>.

==== Responses

*[CDP-IDP02]*

IdP deploymentrs MUST support the issuance of `<saml2p:Response>` messages (with
appropriate status codes) in the event that a user indicates they wish to
cancel/exit or if an error condition occurs, provided that the user agent
remains available.

==== Session Management and Timeouts

*[CDP-IDP03]*

`<saml:AuthnStatement>` elements MUST NOT include a `SessionNotOnOrAfter`
attribute.

*[CDP-IDP04]*

IdPs MUST NOT issue a `<saml:Assertion>` with an `IssueInstant` attribute value
that exceeds the value of the `AuthnInstant` attribute of the included
`<saml:AuthnStatement>` by more than 20 minutes.

_This effectively prohibits the passive fulfilment of authentication requests
(single sign-on) for a subject after 20 minutes have passed since their
most recent authentication event._

Once 20 minutes have passed since the most recent authentication event,
IDPs MUST issue a `<saml:Repsonse>` with a second-level `<samlp:StatusCode>` of
`urn:oasis:names:tc:SAML:2.0:status:NoPassive` in response to any
`<samlp:AuthnRequest>` with an `IsPassive` attribute value of `true` or `1`.

*[CDP-IDP05]*

IdPs participating as a session authority MUST include the `SessionIndex`
attribute of `<saml:AuthnStatement>`.

*[CDP-IDP06]*

IdPs participating as a session authority MUST retain sufficient session state
to sucessfully process `<samlp:LogoutRequest>` messages that specify a
`<samlp:SessionIndex>` value that mathes the `SessionIndex` attribute of any
`<saml:AuthnStatement>` it has issued within the previous 8 hours.

_This ensures that the IdP will be able to propogate single-logout of a
subject's session for up to 8 hours after issuing the last assertion for that
session._

*[CDP-IDP07]*

IdPs participating as a sesson authority MUST administatively perform a global
logout of any current subject's session whenver an authentication event within
that session results in the authentication of a different subject.

_For example, say the IdP has issued an `<saml:AuthnStatement>` for subject A
within the last 8 hours, and subsequently receives a `<samlp:AuthnRequest>` from
the same user agent triggering a new authentication event. If the end-user
authenticates with a different credential (subject B) than the one originally
used by subject A, then the IdP must peform a global logout of subject A's
session, before starting a new session for subject B._