== CATS-Specific Proxy Requirements

*[CDP-PIP01]*

Proxying Identity Provider deployments MUST support the mapping of incoming to
outgoing `<saml:NameID>` elements, to pass through values or map between
different vocabularies as required.

*[CDP-PIP02]*

Proxying Identity Provider deployments MUST support the suppression/eliding of
`<saml:AttributeStatement>` elements from the `<saml:Assertion>` of outgoing
`<samlp:Response>` messages to allow for hiding the identity of the subject
from SPs.

*[CDP-PIP03]*

Proxying Identity Provider deployments MUST support the mapping of incoming to
outgoing `<samlp:RequestedAuthnContext>` and `<samlp:NameIDPolicy>` elements,
to pass through values or map between different vocabularies as required.

*[CDP-PIP04]*

Proxying Identity Provider deployments MUST support the suppression/eliding
of `<samlp:RequesterID>` elements from outgoing `<samlp:AuthnRequest>` messages
to allow for hiding the identity of the Service Provider from proxied Identity
Providers.

*[CDP-PIP05]*

Proxying Identity Provider deployments MUST support the mapping of incoming to
outgoing `<saml:AuthnContext>` elements, to pass through values or map between
different vocabularies as required.

*[CDP-PIP06]*

Proxying Identity Provider deployments MUST support the suppression of
`<saml:AuthenticatingAuthority>` elements from outgoing `<saml:AuthnContext>`
elements to allow for hiding the identity of the proxied Identity Provider from
Service Providers.

*[CDP-PIP07]*

Proxying Identity Provider deployments MUST support the use of a
`<samlp:IDPList>` containing one or more `<samlp:IDPEntry>` elements in incoming
and outgoing `<samlp:AuthnRequest>` messages.

_This allows one proxy in a chain of proxies to provide IdP discovery services
on behalf of other proxies in the chain._

*[CDP-PIP08]*

`<samlp:AuthnRequest>` messages produced by Proxying Identity Provider
deployments MUST include the `ForceAuthn` attribute with a value of `true` or
`1`.

*[CDP-PIP09]*

Proxying Identity Provider deployments participating as a session authority,
that also support the proxying of single logout from a proxied IDP to its own
RPs MUST use the HTTP-Redirect <<SAML2Bind>> binding to receive
`<samlp:LogoutRequest>` messages from the proxied IDP. Any back-channel mechanism,
such at the SOAP binding, MUST NOT be used.

_A proxying IDP must obtain access to the user-agent, so that it can propogate
the logout to its own RPs who require front-channel bindings. Accepting logout
signals from a proxied IDP via any back-channel mechanism such as SOAP would
prevent the proxying IDP from fulfilling its obligations as a session authority
as defined in [SDP-IDP24]._
