== Compliance to the CATS SAML 2.0 Deployment Profiles

The requirements specified are in addition to all normative requirements of the
underlying Web Browser SSO profile <<SAML2Prof>>, as modified by the Approved
Errata <<SAML2Err>>, and readers are assumed to be familiar with all relevant
reference documents. Any such requirements are not repeated here except where
deemed necessary to highlight a point of discussion or draw attention to an
issue addressed in errata, but remain implied.

Note that SAML features that are optional, or lack mandatory processing rules,
are assumed to be optional and out of scope of this profile if not otherwise
precluded or given specific processing rules.

The normative requirements of this CATS Deployment Profile in terms of the
applicable sections of the Kantara Profile are detailed in Sections 4 through 6
of this document. The requirements of <<SAML2Iop>> are repeated word-for-word in
the same order as they appear in the upstream profile. Each requirement is then
annotated with the support required by this profile: typically this is either
“Supported” or “Constrained” or “Not Applicable”. Whenever further details are
required to fully explain the CATS requirement, they are provided.

This profile also has requirements which are additional to the <<SAML2Iop>>
requirements. These are specified at the end of each applicable section, as well
as in section 7.

Deployments owned by Government of Canada departments and agencies MUST obtain
approval from the Chief Information Officer Branch of Treasury Board Secretariat
before ignoring any requirements labelled with the key words "SHOULD", "SHOULD
NOT", "RECOMMENDED" or "NOT RECOMMENDED".